#!/usr/bin/env python3

"""
generate_nex.py

This script extracts substitution model parameters from an IQ-TREE .iqtree file and its corresponding log file, 
and generates a NEXUS-formatted file (.nex) containing model definitions (base model, +I, +G/R, +F, and FMIX components).

Usage:
    python generate_nex.py <iqtree_file> <log_file> [--outdir <output_directory>]

Arguments:
    iqtree_file   Path to the .iqtree file generated by IQ-TREE
    log_file      Path to the corresponding IQ-TREE .log file
    --outdir      Optional. Directory to save the output .nex file (default: current directory)

Example:
    python generate_nex.py example.iqtree example.log --outdir ./models

The output will be a <basename>_parameter.nex file containing the model block in NEXUS format.
"""

import re
import argparse
import os


def parse_args():
    parser = argparse.ArgumentParser(description="Generate NEX file from IQ-TREE and log file.")
    parser.add_argument("iqtree_file", type=str, help="Path to the .iqtree file")
    parser.add_argument("log_file", type=str, help="Path to the log file")
    parser.add_argument("--outdir", type=str, default=".", help="Output directory (relative to current working directory)")
    return parser.parse_args()


def extract_modelname_and_basemodel(log_file):
    with open(log_file, 'r') as file:
        for line in file:
            match = re.search(r'Command:\s*(.+)', line)
            if match:
                command = match.group(1)
                model_match = re.search(r'-m\s+([^\s]+)', command)
                if model_match:
                    full_model = model_match.group(1)
                    modelname = full_model.replace('+', '_').replace('.', '_')
                    basemodel = full_model.split('+')[0]  # Preserve Q.PLANT etc.
                    return modelname, basemodel
    return "Unknown_Model", "Q"


def parse_iqtree(iqtree_file):
    model_info = {}
    freqs = []
    mix_components = []

    with open(iqtree_file, 'r') as file:
        lines = file.readlines()

    in_substitution_process = False
    free_n = None
    gamma_alpha = None
    gamma_n = None

    for i, line in enumerate(lines):
        if "Proportion of invariable sites:" in line:
            inv_sites = re.search(r": ([0-9.]+)", line).group(1)
            model_info['I'] = f"I{{{inv_sites}}}"

        elif "Gamma with" in line:
            gamma_n = re.search(r"Gamma with (\d+) categories", line).group(1)

        elif "Gamma shape alpha:" in line:
            gamma_alpha = re.search(r"Gamma shape alpha: ([0-9.]+)", line).group(1)
            if gamma_n:
                model_info['R'] = f"G{gamma_n}{{{gamma_alpha}}}"

        elif "FreeRate with" in line:
            free_n = re.search(r"FreeRate with (\d+) categories", line).group(1)

        elif "Site proportion and rates:" in line:
            proportions_rates = re.findall(r"\(([^)]+)\)", line)
            values = ','.join([val.strip() for pr in proportions_rates for val in pr.split(',')])
            if free_n:
                model_info['R'] = f"R{free_n}{{{values}}}"

        elif "State frequencies: (empirical counts from alignment)" in line:
            freq_block = lines[i+1:i+22]
            for freq_line in freq_block:
                freq_match = re.search(r"= ([0-9.]+)", freq_line)
                if freq_match:
                    freqs.append(freq_match.group(1))

        elif 'SUBSTITUTION PROCESS' in line:
            in_substitution_process = True
            continue

        if in_substitution_process:
            if re.match(r'^\s+\d+', line):
                fields = line.strip().split()
                comp_info = fields[1]
                rate = fields[2]
                weight = fields[3]

                if weight == '0.0000':
                    weight = '0.00005'

                # Extract component name: remove base model and strip "F" prefix if applicable
                comp_name_raw = comp_info.split('+')[-1]
                comp_name = comp_name_raw.replace('F', '') if comp_name_raw.startswith('F') else comp_name_raw
                if comp_name == '':
                    comp_name = 'F'

                mix_components.append(f"{comp_name}:{rate}:{weight}")
            elif re.match(r'^\s*$', line) and mix_components:
                in_substitution_process = False

    model_info['F'] = freqs
    model_info['MIX'] = mix_components

    return model_info


def build_nex(modelname, model_base, model_info, filename):
    nex_lines = ["#nexus", "begin models;"]

    if model_info['F']:
        freq_line = "frequency F = " + ' '.join(model_info['F']) + ";"
        nex_lines.append(freq_line)

    model_line = f"model {modelname} = {model_base}"
    if 'I' in model_info:
        model_line += f"+{model_info['I']}"
    if 'R' in model_info:
        model_line += f"+{model_info['R']}"

    if model_info['MIX']:
        fmix = "FMIX{" + ','.join(model_info['MIX']) + "};"
        model_line += f"+{fmix}"

    nex_lines.append(model_line)
    nex_lines.append("end;")

    with open(filename, 'w') as nex_file:
        nex_file.write('\n'.join(nex_lines))


if __name__ == "__main__":
    args = parse_args()

    modelname, model_base = extract_modelname_and_basemodel(args.log_file)
    model_info = parse_iqtree(args.iqtree_file)

    output_dir = os.path.abspath(args.outdir)
    os.makedirs(output_dir, exist_ok=True)

    output_filename = os.path.splitext(os.path.basename(args.iqtree_file))[0] + "_parameter.nex"
    output_path = os.path.join(output_dir, output_filename)
    build_nex(modelname, model_base, model_info, output_path)

    print(f"NEX file '{output_path}' generated successfully.")
